import{S as v,i as n,a as M}from"./assets/vendor-77136e93.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const B=document.querySelector(".form"),c=document.querySelector(".js-gallery-grid"),m=document.querySelector(".loader"),u=document.querySelector(".js-load-more-btn");let I=new v(".gallery-grid a",{captionsData:"alt"});B.addEventListener("submit",P);u.addEventListener("click",$);let l=1,d,p=0;async function P(s){var o;if(s.preventDefault(),y(),c.innerHTML="",d=s.target.elements.query.value.trim(),f(),!d){c.innerHTML="",n.error({message:"Search field is empty",position:"topRight"});return}try{l=1;const e=await L();if((o=e==null?void 0:e.hits)!=null&&o.length){h(),p=Math.ceil(e.totalHits/15),g(),w(e.hits);return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){n.info({message:typeof e=="string"?e:"Something went wrong, sorry!",position:"topRight"})}s.target.reset()}async function $(s){var o;f(),b();try{l+=1;const e=await L();if((o=e==null?void 0:e.hits)!=null&&o.length){h(),g(),w(e.hits),document.querySelector(".gallery-card:last-child").scrollIntoView({behavior:"smooth",block:"end"});return}throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){n.info({message:typeof e=="string"?e:"Something went wrong, sorry!",position:"topRight"})}s.target.reset()}function g(){p!==l?y():(b(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}function f(){m.style.display="inline-block"}function h(){m.style.display="none"}function y(){u.classList.remove("hidden")}function b(){u.classList.add("hidden")}async function L(){return(await M.get("https://pixabay.com/api/",{params:{key:"42317586-b983a1ee46e38e925d954d84d",q:d,image_type:"photo",orientation:"horizontal",safeSearch:!0,page:l,per_page:15}})).data}function w(s){const o=s.map(({webformatURL:e,largeImageURL:i,tags:t,likes:r,views:a,comments:S,downloads:q})=>`<a href="${i}" class="gallery-card">
      <img src="${e}" alt="${t}" >
      <div class="img-details-box">
      <p class="detail-item"><b>Likes:</b> ${r}</p>
      <p class="detail-item"><b>Views:</b> ${a}</p>
      <p class="detail-item"><b>Comments:</b> ${S}</p>
      <p class="detail-item"><b>Downloads:</b> ${q}</p></div>
      </a>`).join("");c.insertAdjacentHTML("beforeend",o),I.refresh()}
//# sourceMappingURL=commonHelpers.js.map
